branch-defaults:
  upload-app-to-beanstalk:
    environment: Dev-env
environment-defaults:
  Dev-env:
    branch: upload-app-to-beanstalk
    repository: dimba-api
global:
  application_name: dimba-api
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.5 running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
